### ISSUE TITLE
Assessing simple linear regression model fit and assumptions

### ISSUE THREAD

**Issue by 3mmaRand** [carpentries-incubator/simple-linear-regression-public-health#10]
Assessing simple linear regression model fit and assumptions
https://carpentries-incubator.github.io/simple-linear-regression-public-health/06-fitAndAssumptionSLR/index.html

This is REALLY good! Nice work Ezra! I like how you fully explain the content need at this point but also link to later lessons. I don't think it is too long. I like it

I like the residual explanation - showing a large and small residual makes the concept clear.

Measuring model fit using R2
- can you increase the size of the points or put them on top

In the last sentence before the first exercise:
Therefore, out model
->
Therefore, our model

Exercise: I couldn't find the TotChol_BMI_lm model from episode 2 (or in any other episode). In episode two we have Weight_Height_lm and BPSysAve_AgeMonths_lm. The exercise works well though so you could just remove the reference to episode 2.

1. Validity
I really like the exercise!

2. Representativeness - in the solution 2. there's a "relationshop"

3. Linearity
The effect_plot() function is handy when the model includes a non-linear term! Both the squared and log examples work really well

5. Equal variance of errors (homoscedasticity)
Took me a moment to realise this isn't the child_Weight_Height_lm used earlier, but the first model from https://carpentries-incubator.github.io/simple-linear-regression-public-health/02-singleContPred/index.html. Perhaps when giving the child_Weight_Height_lm exercise, add a sentence along the lines of "in the first lesson we fit a linear regression model of Weight (Weight) as a function of Height (Height) in individuals with an Age (Age) above 17. Here we consider children - individuals with an age below 19." Maybe also use the words adults and children when describing the examples (the difference will register more fully with words than with > 17 and < 19)

Awesome!

**Comment by ezherman** [comment]
Thank you @3mmaRand! I've incorporated these comments. 

I replaced `TotChol_BMI_lm` by `BPSysAve_AgeMonths_lm` in the R^2 challenge. Not sure how the former model got there!
