### ISSUE TITLE
when p is reported as 0.000

### ISSUE THREAD

**Issue by ajstewartlang** [carpentries-incubator/simple-linear-regression-public-health#14]
When p is reported as 0.000 in the model summary is it worth adding a line explaining this should be interpreted as < .001 ?

**Comment by ajstewartlang** [comment]
In this episode (https://carpentries-incubator.github.io/simple-linear-regression-public-health/03-twoLvlFactor/index.html) there is good explanation of `drop_na()` that may be better if it appeared in the first lesson.

**Comment by ajstewartlang** [comment]
When jitter is added to `effect_plot()` does `set.seed()` also need to be specified to ensure people end up with the same plot that's in the episode?

**Comment by ajstewartlang** [comment]
is it worth adding a line explaining that changing the alpha value in `point.alpha` changes the transparency of the points?

**Comment by ezherman** [comment]
Good suggestions, all implemented!
