### ISSUE TITLE
effect_plot jitter affects x and y

### ISSUE THREAD

**Issue by Alanocallaghan** [carpentries-incubator/simple-linear-regression-public-health#19]
The jitter option takes a vector but is given a single value, so it affects the x and y in effect_plot. This is pretty minor here because the range of y is big, but if it's small relative to the jitter size this can make the plots very deceptive.

For example:

``` r
    library("jtools")
mtcars$vs <- factor(mtcars$vs)
lm <- lm(mpg~vs,data=mtcars)

effect_plot(model=lm, pred=vs, plot.points=TRUE, jitter=100, data=mtcars) 
```

![](https://i.imgur.com/P3Zh9zw.png)

``` r
effect_plot(model=lm, pred=vs, plot.points=TRUE, jitter=0.3, data=mtcars)
```

![](https://i.imgur.com/ko1YwqS.png)

``` r
effect_plot(model=lm, pred=vs, plot.points=TRUE, jitter=c(100, 0), data=mtcars) 
```

![](https://i.imgur.com/dO5aci1.png)

``` r
effect_plot(model=lm, pred=vs, plot.points=TRUE, jitter=c(0.3, 0), data=mtcars)
```

![](https://i.imgur.com/4kBPFsL.png)

**Comment by ezherman** [comment]
Well noticed Alan, thank you!

**Comment by Alanocallaghan** [comment]
Cheers, and thanks again for your great work on this course. btw just in case you ever discuss prediction intervals https://github.com/jacob-long/jtools/issues/116
