### ISSUE TITLE
Mistake in the solution for R^2 interpretation? 

### ISSUE THREAD

**Issue by nathansam** [carpentries-incubator/simple-linear-regression-public-health#23]
"Since R^2=0.153 our model accounts for approximately 27% of the variation in BPSysAve".

Shouldn't this should be 15% of the variation? I can push a fix before the lesson if you agree @ezherman . 

Lesson:
https://carpentries-incubator.github.io/simple-linear-regression-public-health/05-fitAndAssumptionSLR/index.html

**Comment by ezherman** [comment]
Agreed and fixed, thanks @nathansam! The R^2 was presented through in-line code but I had forgotten to update the other parts of the section to in-line code.

**Comment by nathansam** [comment]
Brilliant, thanks!
