### ISSUE TITLE
 01-introSLR/index

### ISSUE THREAD

**Issue by 3mmaRand** [carpentries-incubator/simple-linear-regression-public-health#3]
#### 01-introSLR/index ####
https://carpentries-incubator.github.io/simple-linear-regression-public-health/01-introSLR/index.html

We need an intro to the dataset before we get to the exercise. could be in this section of in the Set up.

typo in solution 1 C
C) The outcome variable is pulse and rhe 
-> 
C) The outcome variable is pulse and the

**Comment by ezherman** [comment]
@3mmaRand, do you think there are further things that should be added to data description in the setup?

Further variables can be removed from `dat` and the descriptive table later down the line, when we know for sure that they won't be featured in the workshop.
