### ISSUE TITLE
04-multiLvlFactor/index review

### ISSUE THREAD

**Issue by 3mmaRand** [carpentries-incubator/simple-linear-regression-public-health#6]
https://carpentries-incubator.github.io/simple-linear-regression-public-health/04-multiLvlFactor/index.html

Overview
Questions
How is a simple linear regression model with one multi-level categorical explanatory variable fit in R?
->
How can we fit a simple linear regression model with one multi-level categorical explanatory variable in R?

we first subset our data for working age individuals using filter()
->
we first subset our data for working age individuals using filter() and between()

The filtered data is passed on by data = .. 
->
The filtered data is passed on by the pipe

dat %>%
  filter(Age>15 & Age<65) %>%
  ggplot(., aes(x = Work, y = Age)) +
  geom_violin() + 
  stat_summary(fun = "mean", size = 0.2) +
  stat_summary(fun.data = "mean_cl_normal", geom="errorbar", width=0.2) + 
  xlab("Working status") + 
  scale_x_discrete(labels = c('Looking','Not Working','Working'))
->
[remove .,  add spaces round operators, use between(), use name argument in scale_x_discrete]
dat %>%
  filter(between(Age, 16, 66)) %>%
  ggplot(aes(x = Work, y = Age)) +
  geom_violin() + 
  stat_summary(fun = "mean", size = 0.2) +
  stat_summary(fun.data = "mean_cl_normal", geom = "errorbar", width = 0.2) + 
  scale_x_discrete(name = "Working status", 
                   labels = c('Looking', 'Not Working', 'Working'))

dat %>%
  drop_na(c("Depressed", "Weight")) %>%
  ggplot(., aes(x=Depressed, y=Weight)) +
  geom_violin() +
  stat_summary(fun = "mean", size = 0.2) +
  stat_summary(fun.data = "mean_cl_normal", geom="errorbar", width=0.2) +
  xlab("Number of days a week with depressed feelings")

->
[remove .,  remove quotes round variables, add spaces round operators]
dat %>%
  drop_na(c(Depressed, Weight)) %>%
  ggplot(aes(x = Depressed, y = Weight)) +
  geom_violin() +
  stat_summary(fun = "mean", size = 0.2) +
  stat_summary(fun.data = "mean_cl_normal", geom = "errorbar", width = 0.2) +
  xlab("Number of days a week with depressed feelings")

Age_Work_lm <- dat %>%
  filter(Age>15 & Age<65) %>%
  lm(Age ~ Work, data = .)
->
Age_Work_lm <- dat %>%
  filter(between(Age, 16, 66)) %>%
  lm(formula = Age ~ Work)
[makes a difference to output as 15.# excluded and 65.# included 

Weight_Depressed_lm <- dat %>%
  drop_na(c("Depressed", "Weight")) %>%
  lm(Weight ~ Depressed, data = .)
->
Weight_Depressed_lm <- dat %>%
  drop_na(c(Depressed, Weight)) %>%
  lm(formula = Weight ~ Depressed)

summ(Weight_Depressed_lm, confint = TRUE, digits=3)
->
summ(Weight_Depressed_lm, confint = TRUE, digits = 3)

effect_plot(Age_Work_lm, pred = Work,
            plot.points = TRUE, jitter = 0.3, point.alpha = 0.1) +
  xlab("Working status") + 
  scale_x_discrete(labels = c('Looking','Not Working','Working'))
->
effect_plot(Age_Work_lm, pred = Work,
            plot.points = TRUE, jitter = 0.3, point.alpha = 0.1) +
  scale_x_discrete(name = "Working status",
                   labels = c('Looking','Not Working','Working'))

**Comment by ezherman** [comment]
Resolved with `between(Age, 16, 64)`
